tunnel: 5302c904-e640-40c5-b1f1-5f20b7cce48b
credentials-file: /home/nonroot/.cloudflared/5302c904-e640-40c5-b1f1-5f20b7cce48b.json

ingress:
  - hostname: textbee.dfgworld.net
    service: http://admin-dashboard:4000
  - service: http_status:404
